// Generated by CoffeeScript 1.10.0
(function() {
  fs.writeFile(config.backupLocation + "/" + filename, JSON.stringify(snapshot.exportVal()), function(err) {
    if (err) {
      return console.log(err);
    } else {
      return console.log("The backup was saved! " + filename);
    }
  });

}).call(this);
